-- MySQL Script generated by MySQL Workbench
-- Wed Nov 30 13:03:42 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema DHBW_webpro
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema DHBW_webpro
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DHBW_webpro` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `DHBW_webpro` ;

-- -----------------------------------------------------
-- Table `DHBW_webpro`.`messages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DHBW_webpro`.`messages` (
  `msg_id` INT NOT NULL AUTO_INCREMENT,
  `incoming_msg_id` INT NOT NULL,
  `outgoing_msg_id` INT NOT NULL,
  `msg` VARCHAR(1000) NOT NULL,
  `time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`msg_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `DHBW_webpro`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DHBW_webpro`.`users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `unique_id` INT NOT NULL,
  `fname` VARCHAR(255) NOT NULL,
  `lname` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `img` VARCHAR(255) NOT NULL,
  `status` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
